# Generated by Django 4.1.3 on 2024-01-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0003_rename_item_orderitem_item_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AddField(
            model_name='item',
            name='orders',
            field=models.ManyToManyField(through='bangazonapi.OrderItem', to='bangazonapi.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='bangazonapi.OrderItem', to='bangazonapi.item'),
        ),
    ]
