# Generated by Django 4.1.3 on 2024-01-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0005_remove_item_orders_alter_orderitem_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=255),
        ),
    ]
